- pkg:nuget/xStatic.Netlify@13.0.0
- pkg:nuget/xStatic.Netlify@13.0.1
- pkg:nuget/xStatic.Netlify@13.1.0
- pkg:nuget/xStatic.Netlify@13.1.0-alpha1
- pkg:nuget/xStatic.Netlify@13.1.0-alpha2
- pkg:nuget/xStatic.Netlify@13.1.0-alpha3
- pkg:nuget/xStatic.Netlify@14.0.0
- pkg:nuget/xStatic.Netlify@14.0.0-beta1
- pkg:nuget/xStatic.Netlify@14.0.0-beta2
- pkg:nuget/xStatic.Netlify@14.0.0-beta3
- pkg:nuget/xStatic.Netlify@14.0.0-beta4
- pkg:nuget/xStatic.Netlify@14.1.0
- pkg:nuget/xStatic.Netlify@14.1.0-alpha1
- pkg:nuget/xStatic.Netlify@14.1.0-alpha2
- pkg:nuget/xStatic.Netlify@14.1.1
- pkg:nuget/xStatic.Netlify@14.2.0
- pkg:nuget/xStatic.Netlify@14.2.0-alpha1
- pkg:nuget/xStatic.Netlify@14.2.0-alpha2
- pkg:nuget/xStatic.Netlify@14.2.0-beta1
- pkg:nuget/xStatic.Netlify@14.2.0-beta2
- pkg:nuget/xStatic.Netlify@15.0.0
- pkg:nuget/xStatic.Netlify@15.0.0-alpha1
- pkg:nuget/xStatic.Netlify@15.0.1
- pkg:nuget/xStatic.Netlify@15.0.2
- pkg:nuget/xStatic.Netlify@15.0.3
- pkg:nuget/xStatic.Netlify@15.0.4
- pkg:nuget/xStatic.Netlify@15.1.0
- pkg:nuget/xStatic.Netlify@15.1.0-beta1
- pkg:nuget/xStatic.Netlify@16.0.0-alpha1
- pkg:nuget/xStatic.Netlify@16.0.0-alpha2
- pkg:nuget/xStatic.Netlify@2.0.1-alpha
- pkg:nuget/xStatic.Netlify@2.0.2-alpha
- pkg:nuget/xStatic.Netlify@2.0.3-beta
- pkg:nuget/xStatic.Netlify@3.0.0
- pkg:nuget/xStatic.Netlify@3.0.0-beta
- pkg:nuget/xStatic.Netlify@3.0.1-beta
- pkg:nuget/xStatic.Netlify@3.0.2-beta
- pkg:nuget/xStatic.Netlify@3.0.24-beta
- pkg:nuget/xStatic.Netlify@3.0.25-beta
- pkg:nuget/xStatic.Netlify@3.0.26-beta
- pkg:nuget/xStatic.Netlify@3.1.0
- pkg:nuget/xStatic.Netlify@3.1.1
