- pkg:nuget/LocalAppVeyor@0.5.0-alpha1
- pkg:nuget/LocalAppVeyor@0.5.0-alpha2
- pkg:nuget/LocalAppVeyor@0.5.0-alpha3
- pkg:nuget/LocalAppVeyor@0.5.0-alpha4
- pkg:nuget/LocalAppVeyor@0.5.0-alpha5
- pkg:nuget/LocalAppVeyor@0.5.0-alpha6
