- pkg:nuget/AppVeyorNuGetTest@0.0.4
- pkg:nuget/AppVeyorNuGetTest@0.0.6
- pkg:nuget/AppVeyorNuGetTest@1.0.10
- pkg:nuget/AppVeyorNuGetTest@1.0.13
- pkg:nuget/AppVeyorNuGetTest@1.0.3
- pkg:nuget/AppVeyorNuGetTest@1.0.6
- pkg:nuget/AppVeyorNuGetTest@2.1.0
