- pkg:nuget/Cake.Netlify@0.10.0
- pkg:nuget/Cake.Netlify@0.11.0
- pkg:nuget/Cake.Netlify@0.12.0
- pkg:nuget/Cake.Netlify@0.12.1
- pkg:nuget/Cake.Netlify@0.9.0
- pkg:nuget/Cake.Netlify@0.9.1
- pkg:nuget/Cake.Netlify@0.9.2
