- pkg:nuget/AppVeyorUmbracoPackage@1.1.6-alpha-000011
- pkg:nuget/AppVeyorUmbracoPackage@1.1.6-alpha-000012
- pkg:nuget/AppVeyorUmbracoPackage@1.1.6-alpha-000013
- pkg:nuget/AppVeyorUmbracoPackage@1.1.6-alpha-000014
