- pkg:nuget/prometheus-net.BlackboxMetricServer@1.0.0
- pkg:nuget/prometheus-net.BlackboxMetricServer@1.0.1
- pkg:nuget/prometheus-net.BlackboxMetricServer@1.0.2
- pkg:nuget/prometheus-net.BlackboxMetricServer@1.1.0
- pkg:nuget/prometheus-net.BlackboxMetricServer@1.1.1
