- pkg:nuget/AppMetricsPrometheus@1.0.0
- pkg:nuget/AppMetricsPrometheus@1.0.1
- pkg:nuget/AppMetricsPrometheus@1.0.2
- pkg:nuget/AppMetricsPrometheus@1.0.3
- pkg:nuget/AppMetricsPrometheus@1.0.3-beta-001
- pkg:nuget/AppMetricsPrometheus@1.0.4
