- pkg:nuget/Microsoft.Performance.Toolkit.Plugins.Cloud-Init@1.0.0
- pkg:nuget/Microsoft.Performance.Toolkit.Plugins.Cloud-Init@1.2.0
- pkg:nuget/Microsoft.Performance.Toolkit.Plugins.Cloud-Init@1.2.1
